= Microservices
Microservices are a software component model that works. They are a way of making big
software systems out of little pieces. Little pieces of software are easy to understand, easy to
reason about, and easy to inspect for correctness. -- The Tao of Microservices, Manning, Richard Rodger

== What are Microservices
Microservices involve an architectural approach that emphasizes the decomposition of applications into single-purpose, loosely coupled services managed by 
cross-functional teams, for delivering and maintaining complex software systems with the velocity and quality required by today’s digital business.

Microservices are language-, platform-, and operating system-agnostic. They break down a big monolithic application, typically packaged as a single archive, 
into smaller and simpler applications. Each application does one thing, and does it well, so the “micro” in microservices refers to the scope of the services’ 
functionalities, as opposed to the number of Lines of Code (LOC).

Each application is built by a full-stack team, which reduces potential communication mismatch between different teams that could exist otherwise. Microservices
may not be suitable for simpler applications and are better suited for complex applications that have grown over a period of time.

The availability of an application on a mobile device; the frequency with which an application needs to be updated; and the responsiveness of an 
application’s design are a few key factors driving this style of architecture.

The concept behind microservices is similar to Service-oriented Architecture (SOA), which is why this style of architecture has been referred 
to as “SOA with DevOps,” “SOA for hipsters,” and “SOA 2.0”.

NOTE: The definition is by Arun Gupta from DZone RefCardZ Getting Started with Microservices, and much of this text is taken therein.

== Key characteristics
. *Domain Driven Design:* Functional decomposition can be easily ahieved using Eric Evan's DDD approach.
. *Single Responsibility Principle:* Each service is responsible for a single part of the functionality,
and does it well.
. *Explicitly Published Interface:* A producer service publishes an interface that is used by a consumer service.
. *Independent DURS (Deploy, Update, Replace, Scale):* Each service can be independently deployed, updated, replaced, and scaled.
. *Lightweight communication:* REST over HTTP, STOMP over WebSocket, and other similar lightweight protocols are used for communication between services. 

== Benefits
. *Independent scaling:* Each microservice can scale independently via X-axis scaling (cloning with more CPU or memory) and Z-axis scaling (sharding), 
based upon their needs. This is very different from monolithic applications, which may have very different requirements that must be deployed together.
. *Independent upgrades:* Each service can be deployed independent of other services. Any change local to a service can be easily made by a developer 
without requiring coordination with other teams. For example, performance of a service can be improved by changing the underlying implementation. As a 
result this maintains the agility of the microservice. This is also a great enabler of CI/CD.
. *Easy maintenance:* Code in a microservice is restricted to one function and is thus easier to understand. IDEs can load the smaller amounts of code 
more easily, and increased readability can keep developers more productive.
. *Potential heterogeneity and polyglotism:* Developers are free to pick the language and stack that are best suited for their service. This enables one
to rewrite the service using better languages and technologies as opposed to being penalized because of past decisions, and gives freedom of choice when 
picking a technology, tool, or framework.
. *Fault and resource isolation:* A misbehaving service, such as a memory leak or an unclosed database connection, will only affect that service, 
as opposed to an entire monolithic application. This improves fault isolation and limits how much of an application a failure can affect.
. *Improved communication across teams:* A microservice is typically built by a full-stack team. All members related to a domain work together in a single 
team, which significantly improves communication between team members, as they share the same end goal.

== Operational requirements
Microservices are not the silver bullet that will solve all architectural problems in your applications. Implementing microservices may help, but that is
often just the byproduct of refactoring your application and typically rewriting code using guidelines required by this architecture style. True success 
requires significant investment.

. *Service Replication:* Each service needs to replicate, typically using X-axis cloning or Y-axis partitioning. There should be a standard mechanism 
by which services can easily scale based upon metadata. A PaaS, such as OpenShift by Red Hat, can simplify this functionality.
. *Service Discovery:* In a microservice world, multiple services are typically distributed in a PaaS environment. Immutable infrastructure is provided 
by containers or immutable VM images. Services may scale up and down based upon certain pre-defined metrics. The exact address of a service may not be 
known until the service is deployed and ready to be used.{zwsp} +
{zwsp} +
The dynamic nature of a service’s endpoint address is handled by service registration and discovery. Each service registers with a broker and provides
more details about itself (including the endpoint address). Other consumer services then query the broker to find out the location of a service and 
invoke it. There are several ways to register and query services such as ZooKeeper, etcd, consul, Kubernetes, Netflix Eureka, and others.
. *Service Monitoring:* One of the most important aspects of a distributed system is service monitoring and logging. This enables one to take proactive 
action if, for example, a service is consuming unexpected resources. The ELK Stack can aggregate logs from different microservices, provide a consistent 
visualization over them, and make that data available to business users. Other possible tools for distributed logging are Syslog, Logentries, and Loggly.
. *Resiliency:* Software failure will occur, no matter how much and how hard you test. This is all the more important when multiple microservices are 
distributed all over the Internet. The key concern is not “how to avoid failure” but “how to deal with failure.” It’s important for services to 
automatically take corrective action to ensure user experience is not impacted. The Circuit Breaker pattern allows one to build resiliency in 
software—Netflix’s Hystrix and Ribbon are good libraries that implement this pattern.
. *DevOps:* Continuous Integration and Continuous Deployment (CI/CD) are very important in order for microservices-based applications to succeed. These 
practices are required so that errors are identified early, and so little to no coordination is required between different teams building 
different microservices.

== Writing in .NET Core

== Writing in Java
